// @file backend/database/seed/learn-content.js
// Content for the Learn tab. Slugs are the STABLE public ids the mobile client references —
// unit slugs u1..u4 are mapped from onboarding goals in mobile/src/features/onboarding/options.ts
// (`learnUnitId`) and in learn-service.js (`GOAL_TO_UNIT_SLUG`), so don't rename those.
// Add new content by appending to this file and re-running `npm run seed:learn` (idempotent).
//
// Units: u1 budgeting · u2 saving · u3 debt · u4 investing · u5 UPI & digital payments ·
//        u6 taxes · u7 insurance · u8 retirement
// Lesson slugs: the original 14 use `l1..l14`; everything added later uses descriptive
// slugs (e.g. `upi-pin-safety`). Both are fine — slugs only have to be unique.
//
// Exercise types (validated by services/learn-service.js):
//   multiple_choice → options: string[], answer: index into options
//   true_false     → answer: boolean
//   fill_number    → answer: number, optional tolerance (default 0)
//   order_steps    → options: string[] in the CORRECT order, answer: [0..n-1]
//                    (client shuffles options before display, submits their arrangement
//                    as indices back into the original options array)
//
// Amounts use ₹ (INR) since that's the default currency.

export const UNITS = [
  {
    slug: "u1",
    title: "Budgeting basics",
    description: "Know where every rupee goes.",
    order: 0,
    icon: "pie-chart",
    isPublished: true,
  },
  {
    slug: "u2",
    title: "Saving & emergency funds",
    description: "Build a cushion for life's surprises.",
    order: 1,
    icon: "shield-checkmark",
    isPublished: true,
  },
  {
    slug: "u3",
    title: "Debt & credit",
    description: "Borrow smart, repay faster.",
    order: 2,
    icon: "card",
    isPublished: true,
  },
  {
    slug: "u4",
    title: "Investing 101",
    description: "Make your money work for you.",
    order: 3,
    icon: "trending-up",
    isPublished: true,
  },
  {
    slug: "u5",
    title: "UPI & digital payments",
    description: "Pay safely on your phone.",
    order: 4,
    icon: "phone-portrait",
    isPublished: true,
  },
  {
    slug: "u6",
    title: "Taxes on your salary",
    description: "Understand your payslip and what you keep.",
    order: 5,
    icon: "document-text",
    isPublished: true,
  },
  {
    slug: "u7",
    title: "Insurance basics",
    description: "Protect your income and your health.",
    order: 6,
    icon: "shield-half",
    isPublished: true,
  },
  {
    slug: "u8",
    title: "Retirement & long-term wealth",
    description: "Small amounts, a very long runway.",
    order: 7,
    icon: "hourglass",
    isPublished: true,
  },
];

export const LESSONS = [
  // ---- Unit 1: Budgeting basics ------------------------------------------------------
  {
    slug: "l1",
    unitSlug: "u1",
    order: 0,
    title: "What is a budget?",
    summary: "Income, expenses and the gap between them.",
    xp: 20,
    estimatedMinutes: 3,
    icon: "wallet",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "A budget is a plan for how you will…",
        options: ["Spend and save your money", "Borrow more money", "Avoid thinking about money", "Impress your friends"],
        answer: 0,
        explanation: "A budget is simply a spending and saving plan you decide in advance.",
      },
      {
        type: "true_false",
        prompt: "A budget tells your money where to go before the month starts, instead of wondering where it went.",
        answer: true,
        explanation: "Deciding upfront is the whole point — otherwise the month decides for you.",
      },
      {
        type: "fill_number",
        prompt: "You earn ₹40,000 a month and spend ₹35,000. Your monthly surplus is ₹___.",
        answer: 5000,
        explanation: "Income minus expenses = surplus. ₹40,000 − ₹35,000 = ₹5,000.",
      },
      {
        type: "multiple_choice",
        prompt: "Which of these is usually the FIRST step in making a budget?",
        options: ["List your income", "Set a savings target", "Track old receipts", "Cut your morning coffee"],
        answer: 0,
        explanation: "You can't plan what you don't know you have. Start with income.",
      },
      {
        type: "order_steps",
        prompt: "Arrange the steps of building a monthly budget in order.",
        options: [
          "List your income",
          "List your expenses",
          "Compare income vs expenses",
          "Adjust and set targets",
        ],
        answer: [0, 1, 2, 3],
        explanation: "Income → expenses → compare → adjust. Everything else is decoration.",
      },
    ],
  },
  {
    slug: "l2",
    unitSlug: "u1",
    order: 1,
    title: "Needs vs wants",
    summary: "Sort spending so cuts hurt less.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "cart",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Which of these is a NEED, not a want?",
        options: ["Netflix subscription", "Rent", "The newest phone", "Weekend trip"],
        answer: 1,
        explanation: "Needs are essentials — rent, groceries, utilities, transport to work.",
      },
      {
        type: "true_false",
        prompt: "Groceries are a need; dining out is a want.",
        answer: true,
        explanation: "Same food category, different role: one keeps you alive, the other is convenience.",
      },
      {
        type: "multiple_choice",
        prompt: "The main reason to separate needs from wants is to…",
        options: ["Feel guilty about spending", "Know what to cut first when money is tight", "Impress others", "Track receipts faster"],
        answer: 1,
        explanation: "When you're short, wants get cut before needs. Sorting them makes that easy.",
      },
      {
        type: "fill_number",
        prompt: "If your monthly needs total ₹25,000 and your wants total ₹15,000, your total spending is ₹___.",
        answer: 40000,
        explanation: "Just add: 25,000 + 15,000 = 40,000.",
      },
    ],
  },
  {
    slug: "l3",
    unitSlug: "u1",
    order: 2,
    title: "The 50/30/20 rule",
    summary: "A simple split for any salary.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "pie-chart",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "In the 50/30/20 rule, the 50% goes to…",
        options: ["Wants", "Needs", "Savings", "Debt only"],
        answer: 1,
        explanation: "50% for needs (rent, food, transport), 30% for wants, 20% for savings + debt.",
      },
      {
        type: "multiple_choice",
        prompt: "And the 30% is for…",
        options: ["Wants", "Needs", "Savings only", "Insurance"],
        answer: 0,
        explanation: "30% is your fun money — dining out, hobbies, subscriptions.",
      },
      {
        type: "multiple_choice",
        prompt: "The 20% is for…",
        options: ["Wants", "Needs", "Savings and extra debt repayment", "Rent"],
        answer: 2,
        explanation: "Savings first, or accelerating debt payoff beyond the minimums.",
      },
      {
        type: "fill_number",
        prompt: "Your take-home is ₹50,000. Under 50/30/20, your NEEDS budget is ₹___.",
        answer: 25000,
        explanation: "50% of ₹50,000 = ₹25,000.",
      },
      {
        type: "fill_number",
        prompt: "Same ₹50,000 salary — savings + extra debt payments should be at least ₹___.",
        answer: 10000,
        explanation: "20% of ₹50,000 = ₹10,000.",
      },
      {
        type: "true_false",
        prompt: "The 50/30/20 rule is a strict law you must follow exactly.",
        answer: false,
        explanation: "It's a starting point. Adjust the numbers to fit your rent, city and goals.",
      },
    ],
  },
  {
    slug: "l4",
    unitSlug: "u1",
    order: 3,
    title: "Tracking expenses",
    summary: "Build the habit in 2 minutes a day.",
    xp: 30,
    estimatedMinutes: 4,
    icon: "receipt",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The best time to log an expense is…",
        options: ["End of the month from memory", "Right after you spend", "Every Sunday", "Never — just check the balance"],
        answer: 1,
        explanation: "Right after: you remember it, you feel it, it takes 10 seconds.",
      },
      {
        type: "true_false",
        prompt: "You must catch every single rupee for tracking to be useful.",
        answer: false,
        explanation: "Catching 80% is enough to see the pattern. Perfect kills the habit.",
      },
      {
        type: "multiple_choice",
        prompt: "The main goal of tracking is to…",
        options: ["Feel bad about spending", "See patterns you can change", "Impress your accountant", "Punish yourself"],
        answer: 1,
        explanation: "Awareness first — patterns like 'I spend ₹200/day on delivery' are what unlock change.",
      },
      {
        type: "fill_number",
        prompt: "If a ₹200 chai break happens 3 times a week, in 4 weeks that adds up to ₹___.",
        answer: 2400,
        explanation: "200 × 3 × 4 = 2,400. Small daily habits, big monthly numbers.",
      },
      {
        type: "order_steps",
        prompt: "Arrange a simple tracking habit in order.",
        options: ["Note the amount", "Note the category", "Review weekly", "Adjust next month's budget"],
        answer: [0, 1, 2, 3],
        explanation: "Log → categorise → review → adjust. That loop is the whole system.",
      },
    ],
  },
  {
    slug: "l5",
    unitSlug: "u1",
    order: 4,
    title: "Unit checkpoint",
    summary: "Prove it — a quick recap.",
    xp: 50,
    estimatedMinutes: 6,
    icon: "trophy",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Under the 50/30/20 rule, needs should be at most what % of income?",
        options: ["30%", "50%", "70%", "100%"],
        answer: 1,
        explanation: "Needs are capped at 50%. If they're higher, that's your first target for change.",
      },
      {
        type: "true_false",
        prompt: "Spending ₹42,000 on a ₹40,000 income means you have a surplus.",
        answer: false,
        explanation: "That's a ₹2,000 deficit — you're financing life with debt.",
      },
      {
        type: "fill_number",
        prompt: "20% of a ₹30,000 salary set aside for savings equals ₹___.",
        answer: 6000,
        explanation: "0.20 × 30,000 = 6,000.",
      },
      {
        type: "multiple_choice",
        prompt: "Which comes first when building a budget?",
        options: ["Income", "Expenses", "Savings target", "Debt payoff"],
        answer: 0,
        explanation: "Everything is a percentage of income, so income comes first.",
      },
      {
        type: "true_false",
        prompt: "A budget is a one-time exercise you do and forget.",
        answer: false,
        explanation: "A budget is a monthly conversation with yourself — review, adjust, repeat.",
      },
    ],
  },

  // ---- Unit 2: Saving & emergency funds ---------------------------------------------
  {
    slug: "l6",
    unitSlug: "u2",
    order: 0,
    title: "Why save first",
    summary: "Pay yourself before anyone else.",
    xp: 20,
    estimatedMinutes: 3,
    icon: "shield-checkmark",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "\"Pay yourself first\" means…",
        options: ["Pay your own salary before your team's", "Move savings out before you spend the rest", "Buy something for yourself first", "Keep money hidden from your family"],
        answer: 1,
        explanation: "On payday, transfer savings first. What's left is what you spend.",
      },
      {
        type: "true_false",
        prompt: "Saving whatever is 'left over' at month-end usually works better than saving first.",
        answer: false,
        explanation: "Nothing is ever left over. That's why saving first beats saving last.",
      },
      {
        type: "fill_number",
        prompt: "You save 10% of a ₹40,000 monthly income. Ignoring interest, after 6 months you have ₹___.",
        answer: 24000,
        explanation: "10% × 40,000 = 4,000/month. 4,000 × 6 = 24,000.",
      },
    ],
  },
  {
    slug: "l7",
    unitSlug: "u2",
    order: 1,
    title: "Emergency fund size",
    summary: "3–6 months, and how to get there.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "umbrella",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "A typical emergency fund covers how many months of essential expenses?",
        options: ["1 week", "1 month", "3–6 months", "10+ years"],
        answer: 2,
        explanation: "3–6 months of essentials is the widely-used baseline for financial safety.",
      },
      {
        type: "fill_number",
        prompt: "If your monthly essentials are ₹20,000, a 3-month emergency fund is ₹___.",
        answer: 60000,
        explanation: "20,000 × 3 = 60,000. Simple, but seeing the target makes it real.",
      },
      {
        type: "true_false",
        prompt: "An emergency fund should be kept invested in stocks so it grows.",
        answer: false,
        explanation: "Stocks can drop 30% right when you need cash. Emergency funds stay safe and liquid.",
      },
      {
        type: "multiple_choice",
        prompt: "Which of these is a real emergency?",
        options: ["A Diwali sale", "A sudden medical bill", "A new phone launch", "A weekend trip with friends"],
        answer: 1,
        explanation: "Emergencies are unexpected and non-negotiable — medical bills, sudden repairs, job loss.",
      },
    ],
  },
  {
    slug: "l8",
    unitSlug: "u2",
    order: 2,
    title: "Where to keep it",
    summary: "Savings accounts vs liquid funds.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "business",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The best home for an emergency fund is…",
        options: ["A savings account or liquid mutual fund", "A 5-year locked-in FD", "The stock market", "Under your mattress"],
        answer: 0,
        explanation: "You need safety and same-day access. Savings accounts and liquid funds give both.",
      },
      {
        type: "true_false",
        prompt: "A liquid mutual fund typically offers slightly better returns than a savings account, with near-instant access.",
        answer: true,
        explanation: "Withdrawals usually settle within a day, and returns often edge out savings rates.",
      },
      {
        type: "multiple_choice",
        prompt: "The two things that matter most for parking an emergency fund are…",
        options: ["Growth and status", "Safety and access", "Tax breaks and complexity", "Referral bonuses and gifts"],
        answer: 1,
        explanation: "Everything else is nice-to-have. If it isn't safe and accessible, it isn't emergency money.",
      },
    ],
  },

  // ---- Unit 3: Debt & credit --------------------------------------------------------
  {
    slug: "l9",
    unitSlug: "u3",
    order: 0,
    title: "How interest works",
    summary: "Why a 3% monthly rate is 36% a year.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "calculator",
    exercises: [
      {
        type: "fill_number",
        prompt: "A credit card charges 3% per month. The simple annual rate is ___%.",
        answer: 36,
        explanation: "3 × 12 = 36. Actual APR with compounding is even higher.",
      },
      {
        type: "true_false",
        prompt: "Compound interest means interest starts earning interest of its own.",
        answer: true,
        explanation: "Great when you're saving, brutal when you're borrowing.",
      },
      {
        type: "multiple_choice",
        prompt: "Paying only the 'minimum payment' on a credit card…",
        options: ["Clears the balance in one shot", "Buys time but grows your debt", "Skips interest this month", "Improves your score by itself"],
        answer: 1,
        explanation: "Minimum payments barely cover interest — the balance keeps growing.",
      },
      {
        type: "fill_number",
        prompt: "Simple interest on ₹10,000 at 12% per year, for one year, is ₹___.",
        answer: 1200,
        explanation: "10,000 × 0.12 × 1 = 1,200.",
      },
    ],
  },
  {
    slug: "l10",
    unitSlug: "u3",
    order: 1,
    title: "Snowball vs avalanche",
    summary: "Two proven ways to clear debt.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "layers",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "In the snowball method, you pay off debts starting from…",
        options: ["Biggest balance first", "Smallest balance first", "Highest interest rate", "Longest tenure"],
        answer: 1,
        explanation: "Smallest first — quick wins build momentum and motivation.",
      },
      {
        type: "multiple_choice",
        prompt: "In the avalanche method, you pay off debts starting from…",
        options: ["Biggest balance first", "Smallest balance first", "Highest interest rate", "Oldest debt"],
        answer: 2,
        explanation: "Highest rate first — mathematically the cheapest way out.",
      },
      {
        type: "true_false",
        prompt: "Avalanche saves you the most money in the long run.",
        answer: true,
        explanation: "Killing high-rate debt first cuts total interest paid.",
      },
      {
        type: "true_false",
        prompt: "Snowball can be worth it because clearing small debts fast keeps you motivated.",
        answer: true,
        explanation: "Behaviour beats math when the plan you actually stick to is the one that works.",
      },
    ],
  },
  {
    slug: "l11",
    unitSlug: "u3",
    order: 2,
    title: "Your credit score",
    summary: "What moves it, and what doesn't.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "speedometer",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The biggest factor in your credit score is…",
        options: ["Your age", "Payment history", "Your salary", "Number of cards you own"],
        answer: 1,
        explanation: "Paying on time, every time, matters more than anything else.",
      },
      {
        type: "true_false",
        prompt: "Checking your own credit score lowers it.",
        answer: false,
        explanation: "Self-checks (soft pulls) don't affect the score. Only lender-initiated hard pulls do.",
      },
      {
        type: "multiple_choice",
        prompt: "To improve your credit score, you should…",
        options: ["Max out every card", "Skip a payment now and then", "Pay on time and keep credit utilisation low", "Close all your oldest cards"],
        answer: 2,
        explanation: "On-time payments plus low utilisation (under 30%) are the two biggest levers.",
      },
      {
        type: "fill_number",
        prompt: "On a ₹1,00,000 credit limit, staying under 30% utilisation means using at most ₹___.",
        answer: 30000,
        explanation: "30% of 1,00,000 = 30,000.",
      },
    ],
  },

  // ---- Unit 4: Investing 101 --------------------------------------------------------
  {
    slug: "l12",
    unitSlug: "u4",
    order: 0,
    title: "Risk and return",
    summary: "The trade-off behind every investment.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "pulse",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "In investing, higher potential returns almost always come with…",
        options: ["Lower risk", "Higher risk", "No risk at all", "Guaranteed losses"],
        answer: 1,
        explanation: "There is no free lunch — extra return is the reward for taking extra risk.",
      },
      {
        type: "true_false",
        prompt: "Fixed deposits are considered lower risk than stocks.",
        answer: true,
        explanation: "FDs have guaranteed returns; stock prices swing daily.",
      },
      {
        type: "multiple_choice",
        prompt: "'Diversification' means…",
        options: ["Buying one great stock", "Spreading money across different investments", "Timing the market perfectly", "Following hot tips"],
        answer: 1,
        explanation: "Don't put all your eggs in one basket. When one asset drops, another might hold.",
      },
    ],
  },
  {
    slug: "l13",
    unitSlug: "u4",
    order: 1,
    title: "What is a SIP?",
    summary: "Investing a little, every month.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "repeat",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "SIP stands for…",
        options: ["Special Investment Plan", "Systematic Investment Plan", "Small Income Product", "Standard Interest Payment"],
        answer: 1,
        explanation: "Systematic Investment Plan — a fixed amount invested at fixed intervals.",
      },
      {
        type: "true_false",
        prompt: "A SIP means investing a fixed amount at regular intervals, usually monthly.",
        answer: true,
        explanation: "You commit ₹X per month, and the platform buys units for you automatically.",
      },
      {
        type: "fill_number",
        prompt: "A ₹5,000/month SIP for 12 months invests ₹___ before any returns.",
        answer: 60000,
        explanation: "5,000 × 12 = 60,000. Actual value depends on market returns.",
      },
      {
        type: "multiple_choice",
        prompt: "The main benefit of SIPs is…",
        options: ["Guaranteed returns", "Rupee-cost averaging", "Zero fees", "Tax-free returns"],
        answer: 1,
        explanation: "You buy more units when prices are low and fewer when high — averaging out the cost.",
      },
    ],
  },
  {
    slug: "l14",
    unitSlug: "u4",
    order: 2,
    title: "Index funds",
    summary: "Own the whole market, cheaply.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "grid",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "An index fund is designed to…",
        options: ["Beat the market", "Match a market index", "Time the market", "Only hold 5 stocks"],
        answer: 1,
        explanation: "Index funds passively track an index (like the Nifty 50) — no stock picking.",
      },
      {
        type: "true_false",
        prompt: "Index funds usually have lower expense ratios than actively managed funds.",
        answer: true,
        explanation: "No fund manager picking stocks means lower costs, which compound in your favour.",
      },
      {
        type: "multiple_choice",
        prompt: "The Nifty 50 index tracks…",
        options: ["India's 50 largest listed companies", "The top 50 companies worldwide", "50 gold-mining companies", "50 Indian startups"],
        answer: 0,
        explanation: "Nifty 50 = the 50 largest companies on the NSE by market cap.",
      },
    ],
  },

  // ---- Extra depth for existing units -----------------------------------------------
  // Note: lessons above use legacy `l<n>` slugs. Everything from here on uses descriptive
  // slugs — easier to read in URLs and logs. Both work; slugs only need to be unique.
  {
    slug: "automate-savings",
    unitSlug: "u2",
    order: 3,
    title: "Automate your savings",
    summary: "Make saving the default, not a decision.",
    xp: 30,
    estimatedMinutes: 4,
    icon: "sync",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The most reliable way to save every month is to…",
        options: [
          "Set a standing instruction on salary day",
          "Save whatever is left at month end",
          "Keep cash in a drawer",
          "Decide each month based on mood",
        ],
        answer: 0,
        explanation: "Automation removes willpower from the equation — the money moves before you can spend it.",
      },
      {
        type: "true_false",
        prompt: "Scheduling your savings transfer for the day after payday makes you more likely to stick to it.",
        answer: true,
        explanation: "Paying yourself first means savings never compete with the rest of the month's spending.",
      },
      {
        type: "fill_number",
        prompt: "You automate ₹3,000 a month. Ignoring interest, how much is saved after 2 years? ₹___",
        answer: 72000,
        explanation: "3,000 × 24 months = 72,000 — with zero ongoing effort.",
      },
      {
        type: "order_steps",
        prompt: "Put the steps of automating savings in order.",
        options: [
          "Pick a monthly amount you can spare",
          "Open a separate savings account or fund",
          "Set a standing instruction for payday",
          "Review the amount every 6 months",
        ],
        answer: [0, 1, 2, 3],
        explanation: "Decide the amount, give it a home, automate the transfer, then revisit as your income grows.",
      },
    ],
  },
  {
    slug: "market-crashes",
    unitSlug: "u4",
    order: 3,
    title: "When markets crash",
    summary: "What to do when your portfolio turns red.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "trending-down",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Markets fall 20% and your SIP is down. The usually-best action is to…",
        options: ["Stop the SIP", "Sell everything", "Keep investing as planned", "Borrow money to invest more"],
        answer: 2,
        explanation: "Continuing your SIP through a fall buys more units cheaply — that's rupee-cost averaging working.",
      },
      {
        type: "true_false",
        prompt: "A fall in price is only a real loss once you sell.",
        answer: true,
        explanation: "Until you sell, it is a paper loss. Selling in panic is what converts it into a permanent one.",
      },
      {
        type: "multiple_choice",
        prompt: "Money you need within the next year should be…",
        options: ["In equity for growth", "In safe, liquid options", "In crypto", "In a locked-in 10-year plan"],
        answer: 1,
        explanation: "Short-horizon money has no time to recover from a crash, so it stays out of equity.",
      },
      {
        type: "fill_number",
        prompt: "An investment falls from ₹1,00,000 to ₹80,000. What percentage has it fallen? ___%",
        answer: 20,
        explanation: "A ₹20,000 fall on ₹1,00,000 is 20%. Note it then needs a 25% gain to get back to even.",
      },
    ],
  },

  // ---- Unit 5: UPI & digital payments ------------------------------------------------
  {
    slug: "upi-basics",
    unitSlug: "u5",
    order: 0,
    title: "How UPI works",
    summary: "One app, any bank account, instantly.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "phone-portrait",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "UPI lets you send money using…",
        options: ["A UPI ID or QR code", "Only a full account number and IFSC", "A cheque", "A demand draft"],
        answer: 0,
        explanation: "A UPI ID (like name@bank) or a QR code is enough — no account number or IFSC needed.",
      },
      {
        type: "true_false",
        prompt: "Money sent over UPI usually reaches the other person within seconds, 24x7.",
        answer: true,
        explanation: "UPI settles in real time, including nights, weekends and holidays.",
      },
      {
        type: "multiple_choice",
        prompt: "The organisation that runs UPI is…",
        options: ["NPCI", "SEBI", "IRDAI", "TRAI"],
        answer: 0,
        explanation: "The National Payments Corporation of India (NPCI) built and operates UPI.",
      },
      {
        type: "true_false",
        prompt: "You can link more than one bank account to the same UPI app.",
        answer: true,
        explanation: "Most apps let you add several accounts and pick which one to pay from.",
      },
      {
        type: "multiple_choice",
        prompt: "For normal person-to-person UPI transfers, users are typically charged…",
        options: ["Nothing", "2% of the amount", "A flat ₹50", "₹10 per transfer"],
        answer: 0,
        explanation: "P2P UPI transfers are free for users — one big reason UPI spread so fast.",
      },
    ],
  },
  {
    slug: "upi-pin-safety",
    unitSlug: "u5",
    order: 1,
    title: "Your UPI PIN, explained",
    summary: "The one rule that stops most fraud.",
    xp: 30,
    estimatedMinutes: 4,
    icon: "keypad",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "You need to enter your UPI PIN when you…",
        options: ["Send money", "Receive money", "Check your balance only", "Share your UPI ID"],
        answer: 0,
        explanation: "A PIN authorises money LEAVING your account. Receiving never needs it.",
      },
      {
        type: "true_false",
        prompt: "If someone says \"enter your UPI PIN to receive the money I'm sending you\", it is a scam.",
        answer: true,
        explanation: "Receiving money never requires a PIN. Anyone asking is trying to pull money out of your account.",
      },
      {
        type: "multiple_choice",
        prompt: "A stranger sends you a \"collect request\" for ₹5,000 saying it will credit your account. You should…",
        options: ["Decline it", "Approve it and enter your PIN", "Approve it without a PIN", "Forward it to a friend"],
        answer: 0,
        explanation: "Approving a collect request DEBITS you. Genuine incoming payments need no action from you.",
      },
      {
        type: "true_false",
        prompt: "It is safe to share your UPI PIN with bank staff who call you.",
        answer: false,
        explanation: "No bank, app or official will ever ask for your UPI PIN. Anyone who does is a fraudster.",
      },
      {
        type: "order_steps",
        prompt: "You get an unexpected call claiming a refund needs your PIN. Order the right response.",
        options: [
          "Refuse to share the PIN",
          "End the call",
          "Check the app or account yourself",
          "Report the number to your bank",
        ],
        answer: [0, 1, 2, 3],
        explanation: "Never share, hang up, verify independently, then report so others are protected.",
      },
    ],
  },
  {
    slug: "upi-limits",
    unitSlug: "u5",
    order: 2,
    title: "Limits and failed payments",
    summary: "Why a transfer gets declined, and what happens next.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "speedometer",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "For most banks, the standard UPI limit for a normal person-to-person transfer is about…",
        options: ["₹1,00,000 per day", "₹500 per day", "₹10,00,000 per day", "There is no limit"],
        answer: 0,
        explanation: "₹1 lakh a day is the common baseline, though the exact cap varies by bank and category.",
      },
      {
        type: "true_false",
        prompt: "If a UPI payment fails but your account is debited, the money is normally auto-reversed.",
        answer: true,
        explanation: "Failed transactions are reversed automatically, usually within a few days.",
      },
      {
        type: "multiple_choice",
        prompt: "The safest first step when a UPI payment fails is to…",
        options: [
          "Check your bank statement before retrying",
          "Retry immediately five times",
          "Assume it worked",
          "Uninstall the app",
        ],
        answer: 0,
        explanation: "Confirm whether you were actually debited first, so you don't end up paying twice.",
      },
      {
        type: "true_false",
        prompt: "Banks also cap the NUMBER of UPI transactions you can make in a day, not just the amount.",
        answer: true,
        explanation: "There is usually a daily transaction count limit as well as a rupee limit.",
      },
    ],
  },
  {
    slug: "upi-autopay",
    unitSlug: "u5",
    order: 3,
    title: "Autopay and mandates",
    summary: "Recurring payments without losing control.",
    xp: 30,
    estimatedMinutes: 4,
    icon: "repeat",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "A UPI autopay mandate is best described as…",
        options: [
          "Standing permission to debit you on a schedule",
          "A one-time payment",
          "A loan",
          "A savings account",
        ],
        answer: 0,
        explanation: "You approve once, then approved amounts are debited automatically until you cancel.",
      },
      {
        type: "true_false",
        prompt: "You can cancel a UPI autopay mandate yourself from your payment app.",
        answer: true,
        explanation: "Mandates are listed in your app and can be paused or revoked at any time.",
      },
      {
        type: "multiple_choice",
        prompt: "Autopay is a good fit for…",
        options: ["A monthly SIP", "A one-off gift to a friend", "Splitting a dinner bill", "Paying a stranger"],
        answer: 0,
        explanation: "Predictable, recurring, intentional payments — SIPs, subscriptions, bills.",
      },
      {
        type: "true_false",
        prompt: "Reviewing your active mandates every few months is a good habit.",
        answer: true,
        explanation: "Forgotten subscriptions are one of the quietest ways money leaks out of a budget.",
      },
    ],
  },
  {
    slug: "digital-money-hygiene",
    unitSlug: "u5",
    order: 4,
    title: "Digital money hygiene",
    summary: "Small habits that keep your accounts safe.",
    xp: 50,
    estimatedMinutes: 5,
    icon: "lock-closed",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The safest way to open your bank's app is…",
        options: [
          "From the app you installed from the official store",
          "A link sent over SMS",
          "A link in a WhatsApp forward",
          "A link in an email from an unknown sender",
        ],
        answer: 0,
        explanation: "Always start from the app or a bookmark you control — links are how phishing begins.",
      },
      {
        type: "true_false",
        prompt: "Installing a \"screen sharing\" or remote-access app at a caller's request is dangerous.",
        answer: true,
        explanation: "Screen sharing lets a fraudster watch you type your PIN and OTP in real time.",
      },
      {
        type: "multiple_choice",
        prompt: "An OTP should be shared with…",
        options: ["No one", "Bank staff", "A delivery agent", "A tech support caller"],
        answer: 0,
        explanation: "An OTP is a one-time key to your money. Nobody legitimate will ever ask you for it.",
      },
      {
        type: "true_false",
        prompt: "Turning on transaction alerts helps you spot fraud faster.",
        answer: true,
        explanation: "The sooner you notice an unknown debit, the better your chances of getting it reversed.",
      },
      {
        type: "multiple_choice",
        prompt: "If money leaves your account without your consent, you should first…",
        options: [
          "Report it to your bank immediately",
          "Wait a week to see if it returns",
          "Post about it online",
          "Change nothing",
        ],
        answer: 0,
        explanation: "Reporting fast matters — unauthorised-transaction protections depend on prompt reporting.",
      },
    ],
  },

  // ---- Unit 6: Taxes on your salary --------------------------------------------------
  {
    slug: "salary-slip",
    unitSlug: "u6",
    order: 0,
    title: "Reading your salary slip",
    summary: "CTC, gross, net — and why they differ.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "receipt",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The amount that actually reaches your bank account is your…",
        options: ["Net / take-home pay", "CTC", "Gross salary", "Basic pay"],
        answer: 0,
        explanation: "Net pay is gross salary minus deductions like tax and provident fund.",
      },
      {
        type: "true_false",
        prompt: "Your CTC is usually higher than the money you actually receive in a year.",
        answer: true,
        explanation: "CTC includes employer contributions and benefits that never hit your account as cash.",
      },
      {
        type: "fill_number",
        prompt: "Gross monthly salary ₹60,000, total deductions ₹9,000. Take-home is ₹___",
        answer: 51000,
        explanation: "60,000 − 9,000 = 51,000.",
      },
      {
        type: "multiple_choice",
        prompt: "Which of these is usually a DEDUCTION on a payslip?",
        options: ["Provident fund", "House rent allowance", "Basic pay", "Special allowance"],
        answer: 0,
        explanation: "PF is deducted from your salary; the others are components that make it up.",
      },
    ],
  },
  {
    slug: "tds-and-form16",
    unitSlug: "u6",
    order: 1,
    title: "TDS and Form 16",
    summary: "Tax that's already been paid for you.",
    xp: 30,
    estimatedMinutes: 4,
    icon: "document-text",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "TDS stands for…",
        options: ["Tax Deducted at Source", "Total Daily Savings", "Tax Due Statement", "Transfer Deposit Slip"],
        answer: 0,
        explanation: "Your employer deducts estimated tax from each salary and deposits it with the government.",
      },
      {
        type: "true_false",
        prompt: "Form 16 is the certificate from your employer showing salary paid and tax deducted.",
        answer: true,
        explanation: "It is the main document you use when filing your return on salary income.",
      },
      {
        type: "multiple_choice",
        prompt: "If more TDS was deducted than you actually owed, you…",
        options: ["Claim a refund when filing your return", "Lose the money", "Must pay it again", "Get nothing back"],
        answer: 0,
        explanation: "Filing your return reconciles what was deducted against what you owed, and refunds the excess.",
      },
      {
        type: "true_false",
        prompt: "Because TDS was deducted, you never need to file an income tax return.",
        answer: false,
        explanation: "TDS is only an estimate. Filing is what finalises your tax and releases any refund.",
      },
    ],
  },
  {
    slug: "tax-regimes",
    unitSlug: "u6",
    order: 2,
    title: "Old vs new tax regime",
    summary: "Lower rates, or more deductions?",
    xp: 30,
    estimatedMinutes: 5,
    icon: "git-compare",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The core trade-off between the two regimes is…",
        options: [
          "Lower rates with fewer deductions vs higher rates with more deductions",
          "One is only for businesses",
          "One is illegal",
          "There is no difference",
        ],
        answer: 0,
        explanation: "The new regime cuts rates but removes most exemptions; the old one keeps deductions at higher rates.",
      },
      {
        type: "true_false",
        prompt: "Someone who claims very few deductions is usually better off in the new regime.",
        answer: true,
        explanation: "With little to deduct, the lower headline rates generally win.",
      },
      {
        type: "true_false",
        prompt: "Someone paying large home-loan interest and using the full 80C limit may still prefer the old regime.",
        answer: true,
        explanation: "Big deductions can outweigh the new regime's lower rates — it's worth comparing both.",
      },
      {
        type: "multiple_choice",
        prompt: "The right way to decide between regimes is to…",
        options: [
          "Calculate your tax under both and pick the lower",
          "Always pick the new one",
          "Always pick the old one",
          "Ask a colleague what they chose",
        ],
        answer: 0,
        explanation: "It depends entirely on your own deductions. Run both numbers.",
      },
    ],
  },
  {
    slug: "tax-saving-sections",
    unitSlug: "u6",
    order: 3,
    title: "Common tax-saving sections",
    summary: "80C, 80D and the rest, in plain terms.",
    xp: 50,
    estimatedMinutes: 6,
    icon: "pricetags",
    exercises: [
      {
        type: "fill_number",
        prompt: "The maximum deduction under Section 80C is ₹___ lakh.",
        answer: 1.5,
        tolerance: 0,
        explanation: "80C is capped at ₹1.5 lakh a year across all eligible investments together.",
      },
      {
        type: "multiple_choice",
        prompt: "Which of these typically qualifies under Section 80C?",
        options: ["PPF contributions", "Your grocery bills", "A holiday", "Your phone recharge"],
        answer: 0,
        explanation: "PPF, EPF, ELSS, life insurance premiums and principal on a home loan are common 80C items.",
      },
      {
        type: "multiple_choice",
        prompt: "Section 80D covers deductions for…",
        options: ["Health insurance premiums", "Petrol", "Rent paid", "Gold purchases"],
        answer: 0,
        explanation: "80D is specifically for medical insurance premiums for you and your family.",
      },
      {
        type: "true_false",
        prompt: "The 80C limit applies to all your eligible investments added together, not to each one separately.",
        answer: true,
        explanation: "It is one shared ceiling — ₹1.5 lakh total, however you split it.",
      },
      {
        type: "true_false",
        prompt: "A bad investment becomes a good one simply because it saves tax.",
        answer: false,
        explanation: "Tax relief is a bonus, not a reason. Judge the investment on its own merits first.",
      },
    ],
  },

  // ---- Unit 7: Insurance basics ------------------------------------------------------
  {
    slug: "why-insurance",
    unitSlug: "u7",
    order: 0,
    title: "What insurance is for",
    summary: "Transferring risks you can't absorb.",
    xp: 20,
    estimatedMinutes: 3,
    icon: "shield-half",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The purpose of insurance is to…",
        options: [
          "Protect you from losses too big to absorb",
          "Make you rich",
          "Beat the stock market",
          "Save tax and nothing else",
        ],
        answer: 0,
        explanation: "You pay a small, known premium to avoid a rare but financially devastating loss.",
      },
      {
        type: "true_false",
        prompt: "Insurance is a bad deal if you never claim.",
        answer: false,
        explanation: "Not claiming means the bad thing didn't happen. You bought certainty, and it worked.",
      },
      {
        type: "multiple_choice",
        prompt: "Which risk is best handled by insurance rather than savings?",
        options: [
          "A major hospitalisation",
          "A new phone next year",
          "This month's groceries",
          "A weekend trip",
        ],
        answer: 0,
        explanation: "Rare, huge, unpredictable costs are exactly what insurance exists for.",
      },
    ],
  },
  {
    slug: "term-vs-endowment",
    unitSlug: "u7",
    order: 1,
    title: "Term vs endowment",
    summary: "Why mixing insurance and investment costs you.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "git-compare",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Term insurance is best described as…",
        options: [
          "Pure life cover with no maturity payout",
          "A savings plan with bonuses",
          "A mutual fund",
          "A fixed deposit",
        ],
        answer: 0,
        explanation: "You pay only for protection, which is why the cover is so large for such a small premium.",
      },
      {
        type: "true_false",
        prompt: "For the same premium, term insurance gives far more life cover than an endowment plan.",
        answer: true,
        explanation: "Endowment premiums are split between cover and investment, so the cover shrinks.",
      },
      {
        type: "multiple_choice",
        prompt: "A common rule of thumb for life cover is…",
        options: [
          "About 10–15 times your annual income",
          "Exactly one month's salary",
          "₹1 lakh for everyone",
          "Half your age in lakhs",
        ],
        answer: 0,
        explanation: "Enough that your dependants could replace your income for many years.",
      },
      {
        type: "true_false",
        prompt: "Someone with no financial dependants has an urgent need for large life insurance.",
        answer: false,
        explanation: "Life cover replaces income for people who rely on you. No dependants, much less need.",
      },
      {
        type: "multiple_choice",
        prompt: "Buying term cover and investing the difference separately usually gives you…",
        options: [
          "Better cover and better returns",
          "Worse cover and worse returns",
          "Identical outcomes",
          "No cover at all",
        ],
        answer: 0,
        explanation: "Keeping protection and investing separate lets each job be done well and cheaply.",
      },
    ],
  },
  {
    slug: "health-insurance",
    unitSlug: "u7",
    order: 2,
    title: "Health insurance essentials",
    summary: "The terms that decide whether you're actually covered.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "medkit",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "A \"cashless\" hospital claim means…",
        options: [
          "The insurer settles directly with a network hospital",
          "You get cash in hand",
          "Treatment is free for everyone",
          "You pay nothing ever again",
        ],
        answer: 0,
        explanation: "At network hospitals the insurer pays the bill directly, so you don't fund it upfront.",
      },
      {
        type: "true_false",
        prompt: "Pre-existing conditions usually have a waiting period before they're covered.",
        answer: true,
        explanation: "Typically a few years, which is exactly why buying health cover early matters.",
      },
      {
        type: "multiple_choice",
        prompt: "Relying only on your employer's health cover is risky because…",
        options: [
          "It ends when the job does",
          "It is always too large",
          "It covers your whole city",
          "It never expires",
        ],
        answer: 0,
        explanation: "Losing or changing a job can leave you uninsured exactly when you're most stretched.",
      },
      {
        type: "true_false",
        prompt: "A room-rent limit in a policy can reduce how much of your bill gets paid.",
        answer: true,
        explanation: "Exceeding sub-limits often means proportionate deductions across the whole claim.",
      },
    ],
  },
  {
    slug: "making-a-claim",
    unitSlug: "u7",
    order: 3,
    title: "Making a claim",
    summary: "What to do before you ever need to.",
    xp: 50,
    estimatedMinutes: 5,
    icon: "clipboard",
    exercises: [
      {
        type: "order_steps",
        prompt: "Order the steps of a planned cashless hospital claim.",
        options: [
          "Choose a network hospital",
          "Inform the insurer or TPA before admission",
          "Share your policy and ID at the hospital desk",
          "Insurer approves and settles the bill",
        ],
        answer: [0, 1, 2, 3],
        explanation: "Network hospital, pre-intimation, documents, then settlement.",
      },
      {
        type: "true_false",
        prompt: "Declaring your medical history honestly when buying a policy protects your future claims.",
        answer: true,
        explanation: "Non-disclosure is one of the most common reasons claims get rejected.",
      },
      {
        type: "multiple_choice",
        prompt: "A high claim settlement ratio suggests the insurer…",
        options: [
          "Pays most of the claims it receives",
          "Has the cheapest premiums",
          "Has the most branches",
          "Advertises the most",
        ],
        answer: 0,
        explanation: "It's a useful signal of how reliably an insurer actually pays out.",
      },
      {
        type: "true_false",
        prompt: "Keeping your policy documents and insurer helpline saved somewhere accessible is worth doing now.",
        answer: true,
        explanation: "You'll need them under stress — a hospital desk is a bad place to be hunting for paperwork.",
      },
    ],
  },

  // ---- Unit 8: Retirement & long-term wealth -----------------------------------------
  {
    slug: "compounding",
    unitSlug: "u8",
    order: 0,
    title: "The power of compounding",
    summary: "Why starting early beats investing more.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "trending-up",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Compounding means your returns…",
        options: ["Start earning returns of their own", "Are paid out in cash", "Stay flat", "Are taxed twice"],
        answer: 0,
        explanation: "Growth on top of previous growth — which is why time matters more than timing.",
      },
      {
        type: "fill_number",
        prompt: "By the Rule of 72, money growing at 12% a year doubles in roughly ___ years.",
        answer: 6,
        explanation: "72 ÷ 12 = 6. A quick mental estimate for doubling time.",
      },
      {
        type: "fill_number",
        prompt: "By the same rule, at 8% a year money doubles in roughly ___ years.",
        answer: 9,
        explanation: "72 ÷ 8 = 9.",
      },
      {
        type: "true_false",
        prompt: "Starting to invest 10 years earlier can beat investing a larger amount later.",
        answer: true,
        explanation: "Extra years give compounding more doublings, which is hard to catch up with later.",
      },
    ],
  },
  {
    slug: "epf-basics",
    unitSlug: "u8",
    order: 1,
    title: "EPF: your default retirement fund",
    summary: "The money already being saved for you.",
    xp: 30,
    estimatedMinutes: 4,
    icon: "business",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "EPF is…",
        options: [
          "A retirement fund built from salary and employer contributions",
          "A type of health insurance",
          "A stock market index",
          "A credit card",
        ],
        answer: 0,
        explanation: "Both you and your employer contribute every month, and it earns interest until retirement.",
      },
      {
        type: "fill_number",
        prompt: "An employee's standard EPF contribution is ___% of basic salary.",
        answer: 12,
        explanation: "12% of basic pay is the usual employee contribution, with the employer adding its share.",
      },
      {
        type: "true_false",
        prompt: "You can transfer your EPF balance when you change jobs instead of withdrawing it.",
        answer: true,
        explanation: "Transferring keeps the money compounding — withdrawing early resets that progress.",
      },
      {
        type: "multiple_choice",
        prompt: "Withdrawing your EPF every time you switch jobs mainly costs you…",
        options: ["Decades of compounding", "Nothing at all", "Your salary", "Your health cover"],
        answer: 0,
        explanation: "It converts long-term retirement money into short-term spending money.",
      },
    ],
  },
  {
    slug: "ppf-and-nps",
    unitSlug: "u8",
    order: 2,
    title: "PPF and NPS",
    summary: "Two long-horizon options worth knowing.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "layers",
    exercises: [
      {
        type: "fill_number",
        prompt: "A PPF account has a lock-in of ___ years.",
        answer: 15,
        explanation: "15 years, which is what makes it a genuinely long-term, low-risk option.",
      },
      {
        type: "multiple_choice",
        prompt: "PPF is best described as…",
        options: [
          "A government-backed long-term savings scheme",
          "A stock trading account",
          "A credit product",
          "A short-term deposit",
        ],
        answer: 0,
        explanation: "Government-backed, fixed interest, very long horizon.",
      },
      {
        type: "multiple_choice",
        prompt: "NPS differs from PPF mainly because NPS…",
        options: [
          "Invests partly in market-linked assets",
          "Has no lock-in",
          "Is only for students",
          "Guarantees a fixed return",
        ],
        answer: 0,
        explanation: "NPS allocates across equity and debt, so returns vary with markets.",
      },
      {
        type: "true_false",
        prompt: "The annual contribution limit for a PPF account is ₹1.5 lakh.",
        answer: true,
        explanation: "₹1.5 lakh per financial year is the maximum you can put into PPF.",
      },
    ],
  },
  {
    slug: "retirement-number",
    unitSlug: "u8",
    order: 3,
    title: "Your retirement number",
    summary: "How much is actually enough.",
    xp: 50,
    estimatedMinutes: 6,
    icon: "flag",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Your retirement target should be based mainly on…",
        options: [
          "Your expected annual expenses",
          "Your current age only",
          "What your friends have saved",
          "Your highest ever salary",
        ],
        answer: 0,
        explanation: "Retirement replaces spending, not income — so expenses are the right starting point.",
      },
      {
        type: "fill_number",
        prompt: "If you expect to spend ₹6,00,000 a year and want 25 times that, your target is ₹___",
        answer: 15000000,
        explanation: "6,00,000 × 25 = ₹1.5 crore. The 25x rule is a common rough starting estimate.",
      },
      {
        type: "true_false",
        prompt: "Inflation means the same lifestyle will cost more each year you get closer to retirement.",
        answer: true,
        explanation: "Any serious retirement plan has to assume rising costs, not today's prices.",
      },
      {
        type: "multiple_choice",
        prompt: "The biggest lever available to a young investor is…",
        options: ["Time in the market", "Picking the perfect stock", "Timing crashes", "Frequent trading"],
        answer: 0,
        explanation: "Years of compounding do more work than any single clever decision.",
      },
      {
        type: "order_steps",
        prompt: "Order the steps of building a retirement plan.",
        options: [
          "Estimate your annual expenses in retirement",
          "Pick a target corpus multiple",
          "Work out the monthly investment needed",
          "Automate it and review yearly",
        ],
        answer: [0, 1, 2, 3],
        explanation: "Expenses, target, monthly amount, then automate and revisit.",
      },
    ],
  },
];
