// @file backend/database/seed/learn-content.js
// Starter content for the Learn tab. Slugs (u1..u4, l1..l14) are the STABLE public ids
// the mobile client references — see mobile/src/features/onboarding/options.ts
// (`learnUnitId`) and features/learn/sampleData.ts. Add new content by appending to
// this file and re-running `npm run seed:learn`.
//
// Exercise types (validated by services/learn-service.js):
//   multiple_choice → options: string[], answer: index into options
//   true_false     → answer: boolean
//   fill_number    → answer: number, optional tolerance (default 0)
//   order_steps    → options: string[] in the CORRECT order, answer: [0..n-1]
//                    (client shuffles options before display, submits their arrangement
//                    as indices back into the original options array)
//
// Amounts use ₹ (INR) since that's the default currency.

export const UNITS = [
  {
    slug: "u1",
    title: "Budgeting basics",
    description: "Know where every rupee goes.",
    order: 0,
    icon: "pie-chart",
    isPublished: true,
  },
  {
    slug: "u2",
    title: "Saving & emergency funds",
    description: "Build a cushion for life's surprises.",
    order: 1,
    icon: "shield-checkmark",
    isPublished: true,
  },
  {
    slug: "u3",
    title: "Debt & credit",
    description: "Borrow smart, repay faster.",
    order: 2,
    icon: "card",
    isPublished: true,
  },
  {
    slug: "u4",
    title: "Investing 101",
    description: "Make your money work for you.",
    order: 3,
    icon: "trending-up",
    isPublished: true,
  },
];

export const LESSONS = [
  // ---- Unit 1: Budgeting basics ------------------------------------------------------
  {
    slug: "l1",
    unitSlug: "u1",
    order: 0,
    title: "What is a budget?",
    summary: "Income, expenses and the gap between them.",
    xp: 20,
    estimatedMinutes: 3,
    icon: "wallet",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "A budget is a plan for how you will…",
        options: ["Spend and save your money", "Borrow more money", "Avoid thinking about money", "Impress your friends"],
        answer: 0,
        explanation: "A budget is simply a spending and saving plan you decide in advance.",
      },
      {
        type: "true_false",
        prompt: "A budget tells your money where to go before the month starts, instead of wondering where it went.",
        answer: true,
        explanation: "Deciding upfront is the whole point — otherwise the month decides for you.",
      },
      {
        type: "fill_number",
        prompt: "You earn ₹40,000 a month and spend ₹35,000. Your monthly surplus is ₹___.",
        answer: 5000,
        explanation: "Income minus expenses = surplus. ₹40,000 − ₹35,000 = ₹5,000.",
      },
      {
        type: "multiple_choice",
        prompt: "Which of these is usually the FIRST step in making a budget?",
        options: ["List your income", "Set a savings target", "Track old receipts", "Cut your morning coffee"],
        answer: 0,
        explanation: "You can't plan what you don't know you have. Start with income.",
      },
      {
        type: "order_steps",
        prompt: "Arrange the steps of building a monthly budget in order.",
        options: [
          "List your income",
          "List your expenses",
          "Compare income vs expenses",
          "Adjust and set targets",
        ],
        answer: [0, 1, 2, 3],
        explanation: "Income → expenses → compare → adjust. Everything else is decoration.",
      },
    ],
  },
  {
    slug: "l2",
    unitSlug: "u1",
    order: 1,
    title: "Needs vs wants",
    summary: "Sort spending so cuts hurt less.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "cart",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Which of these is a NEED, not a want?",
        options: ["Netflix subscription", "Rent", "The newest phone", "Weekend trip"],
        answer: 1,
        explanation: "Needs are essentials — rent, groceries, utilities, transport to work.",
      },
      {
        type: "true_false",
        prompt: "Groceries are a need; dining out is a want.",
        answer: true,
        explanation: "Same food category, different role: one keeps you alive, the other is convenience.",
      },
      {
        type: "multiple_choice",
        prompt: "The main reason to separate needs from wants is to…",
        options: ["Feel guilty about spending", "Know what to cut first when money is tight", "Impress others", "Track receipts faster"],
        answer: 1,
        explanation: "When you're short, wants get cut before needs. Sorting them makes that easy.",
      },
      {
        type: "fill_number",
        prompt: "If your monthly needs total ₹25,000 and your wants total ₹15,000, your total spending is ₹___.",
        answer: 40000,
        explanation: "Just add: 25,000 + 15,000 = 40,000.",
      },
    ],
  },
  {
    slug: "l3",
    unitSlug: "u1",
    order: 2,
    title: "The 50/30/20 rule",
    summary: "A simple split for any salary.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "pie-chart",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "In the 50/30/20 rule, the 50% goes to…",
        options: ["Wants", "Needs", "Savings", "Debt only"],
        answer: 1,
        explanation: "50% for needs (rent, food, transport), 30% for wants, 20% for savings + debt.",
      },
      {
        type: "multiple_choice",
        prompt: "And the 30% is for…",
        options: ["Wants", "Needs", "Savings only", "Insurance"],
        answer: 0,
        explanation: "30% is your fun money — dining out, hobbies, subscriptions.",
      },
      {
        type: "multiple_choice",
        prompt: "The 20% is for…",
        options: ["Wants", "Needs", "Savings and extra debt repayment", "Rent"],
        answer: 2,
        explanation: "Savings first, or accelerating debt payoff beyond the minimums.",
      },
      {
        type: "fill_number",
        prompt: "Your take-home is ₹50,000. Under 50/30/20, your NEEDS budget is ₹___.",
        answer: 25000,
        explanation: "50% of ₹50,000 = ₹25,000.",
      },
      {
        type: "fill_number",
        prompt: "Same ₹50,000 salary — savings + extra debt payments should be at least ₹___.",
        answer: 10000,
        explanation: "20% of ₹50,000 = ₹10,000.",
      },
      {
        type: "true_false",
        prompt: "The 50/30/20 rule is a strict law you must follow exactly.",
        answer: false,
        explanation: "It's a starting point. Adjust the numbers to fit your rent, city and goals.",
      },
    ],
  },
  {
    slug: "l4",
    unitSlug: "u1",
    order: 3,
    title: "Tracking expenses",
    summary: "Build the habit in 2 minutes a day.",
    xp: 30,
    estimatedMinutes: 4,
    icon: "receipt",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The best time to log an expense is…",
        options: ["End of the month from memory", "Right after you spend", "Every Sunday", "Never — just check the balance"],
        answer: 1,
        explanation: "Right after: you remember it, you feel it, it takes 10 seconds.",
      },
      {
        type: "true_false",
        prompt: "You must catch every single rupee for tracking to be useful.",
        answer: false,
        explanation: "Catching 80% is enough to see the pattern. Perfect kills the habit.",
      },
      {
        type: "multiple_choice",
        prompt: "The main goal of tracking is to…",
        options: ["Feel bad about spending", "See patterns you can change", "Impress your accountant", "Punish yourself"],
        answer: 1,
        explanation: "Awareness first — patterns like 'I spend ₹200/day on delivery' are what unlock change.",
      },
      {
        type: "fill_number",
        prompt: "If a ₹200 chai break happens 3 times a week, in 4 weeks that adds up to ₹___.",
        answer: 2400,
        explanation: "200 × 3 × 4 = 2,400. Small daily habits, big monthly numbers.",
      },
      {
        type: "order_steps",
        prompt: "Arrange a simple tracking habit in order.",
        options: ["Note the amount", "Note the category", "Review weekly", "Adjust next month's budget"],
        answer: [0, 1, 2, 3],
        explanation: "Log → categorise → review → adjust. That loop is the whole system.",
      },
    ],
  },
  {
    slug: "l5",
    unitSlug: "u1",
    order: 4,
    title: "Unit checkpoint",
    summary: "Prove it — a quick recap.",
    xp: 50,
    estimatedMinutes: 6,
    icon: "trophy",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "Under the 50/30/20 rule, needs should be at most what % of income?",
        options: ["30%", "50%", "70%", "100%"],
        answer: 1,
        explanation: "Needs are capped at 50%. If they're higher, that's your first target for change.",
      },
      {
        type: "true_false",
        prompt: "Spending ₹42,000 on a ₹40,000 income means you have a surplus.",
        answer: false,
        explanation: "That's a ₹2,000 deficit — you're financing life with debt.",
      },
      {
        type: "fill_number",
        prompt: "20% of a ₹30,000 salary set aside for savings equals ₹___.",
        answer: 6000,
        explanation: "0.20 × 30,000 = 6,000.",
      },
      {
        type: "multiple_choice",
        prompt: "Which comes first when building a budget?",
        options: ["Income", "Expenses", "Savings target", "Debt payoff"],
        answer: 0,
        explanation: "Everything is a percentage of income, so income comes first.",
      },
      {
        type: "true_false",
        prompt: "A budget is a one-time exercise you do and forget.",
        answer: false,
        explanation: "A budget is a monthly conversation with yourself — review, adjust, repeat.",
      },
    ],
  },

  // ---- Unit 2: Saving & emergency funds ---------------------------------------------
  {
    slug: "l6",
    unitSlug: "u2",
    order: 0,
    title: "Why save first",
    summary: "Pay yourself before anyone else.",
    xp: 20,
    estimatedMinutes: 3,
    icon: "shield-checkmark",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "\"Pay yourself first\" means…",
        options: ["Pay your own salary before your team's", "Move savings out before you spend the rest", "Buy something for yourself first", "Keep money hidden from your family"],
        answer: 1,
        explanation: "On payday, transfer savings first. What's left is what you spend.",
      },
      {
        type: "true_false",
        prompt: "Saving whatever is 'left over' at month-end usually works better than saving first.",
        answer: false,
        explanation: "Nothing is ever left over. That's why saving first beats saving last.",
      },
      {
        type: "fill_number",
        prompt: "You save 10% of a ₹40,000 monthly income. Ignoring interest, after 6 months you have ₹___.",
        answer: 24000,
        explanation: "10% × 40,000 = 4,000/month. 4,000 × 6 = 24,000.",
      },
    ],
  },
  {
    slug: "l7",
    unitSlug: "u2",
    order: 1,
    title: "Emergency fund size",
    summary: "3–6 months, and how to get there.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "umbrella",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "A typical emergency fund covers how many months of essential expenses?",
        options: ["1 week", "1 month", "3–6 months", "10+ years"],
        answer: 2,
        explanation: "3–6 months of essentials is the widely-used baseline for financial safety.",
      },
      {
        type: "fill_number",
        prompt: "If your monthly essentials are ₹20,000, a 3-month emergency fund is ₹___.",
        answer: 60000,
        explanation: "20,000 × 3 = 60,000. Simple, but seeing the target makes it real.",
      },
      {
        type: "true_false",
        prompt: "An emergency fund should be kept invested in stocks so it grows.",
        answer: false,
        explanation: "Stocks can drop 30% right when you need cash. Emergency funds stay safe and liquid.",
      },
      {
        type: "multiple_choice",
        prompt: "Which of these is a real emergency?",
        options: ["A Diwali sale", "A sudden medical bill", "A new phone launch", "A weekend trip with friends"],
        answer: 1,
        explanation: "Emergencies are unexpected and non-negotiable — medical bills, sudden repairs, job loss.",
      },
    ],
  },
  {
    slug: "l8",
    unitSlug: "u2",
    order: 2,
    title: "Where to keep it",
    summary: "Savings accounts vs liquid funds.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "business",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The best home for an emergency fund is…",
        options: ["A savings account or liquid mutual fund", "A 5-year locked-in FD", "The stock market", "Under your mattress"],
        answer: 0,
        explanation: "You need safety and same-day access. Savings accounts and liquid funds give both.",
      },
      {
        type: "true_false",
        prompt: "A liquid mutual fund typically offers slightly better returns than a savings account, with near-instant access.",
        answer: true,
        explanation: "Withdrawals usually settle within a day, and returns often edge out savings rates.",
      },
      {
        type: "multiple_choice",
        prompt: "The two things that matter most for parking an emergency fund are…",
        options: ["Growth and status", "Safety and access", "Tax breaks and complexity", "Referral bonuses and gifts"],
        answer: 1,
        explanation: "Everything else is nice-to-have. If it isn't safe and accessible, it isn't emergency money.",
      },
    ],
  },

  // ---- Unit 3: Debt & credit --------------------------------------------------------
  {
    slug: "l9",
    unitSlug: "u3",
    order: 0,
    title: "How interest works",
    summary: "Why a 3% monthly rate is 36% a year.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "calculator",
    exercises: [
      {
        type: "fill_number",
        prompt: "A credit card charges 3% per month. The simple annual rate is ___%.",
        answer: 36,
        explanation: "3 × 12 = 36. Actual APR with compounding is even higher.",
      },
      {
        type: "true_false",
        prompt: "Compound interest means interest starts earning interest of its own.",
        answer: true,
        explanation: "Great when you're saving, brutal when you're borrowing.",
      },
      {
        type: "multiple_choice",
        prompt: "Paying only the 'minimum payment' on a credit card…",
        options: ["Clears the balance in one shot", "Buys time but grows your debt", "Skips interest this month", "Improves your score by itself"],
        answer: 1,
        explanation: "Minimum payments barely cover interest — the balance keeps growing.",
      },
      {
        type: "fill_number",
        prompt: "Simple interest on ₹10,000 at 12% per year, for one year, is ₹___.",
        answer: 1200,
        explanation: "10,000 × 0.12 × 1 = 1,200.",
      },
    ],
  },
  {
    slug: "l10",
    unitSlug: "u3",
    order: 1,
    title: "Snowball vs avalanche",
    summary: "Two proven ways to clear debt.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "layers",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "In the snowball method, you pay off debts starting from…",
        options: ["Biggest balance first", "Smallest balance first", "Highest interest rate", "Longest tenure"],
        answer: 1,
        explanation: "Smallest first — quick wins build momentum and motivation.",
      },
      {
        type: "multiple_choice",
        prompt: "In the avalanche method, you pay off debts starting from…",
        options: ["Biggest balance first", "Smallest balance first", "Highest interest rate", "Oldest debt"],
        answer: 2,
        explanation: "Highest rate first — mathematically the cheapest way out.",
      },
      {
        type: "true_false",
        prompt: "Avalanche saves you the most money in the long run.",
        answer: true,
        explanation: "Killing high-rate debt first cuts total interest paid.",
      },
      {
        type: "true_false",
        prompt: "Snowball can be worth it because clearing small debts fast keeps you motivated.",
        answer: true,
        explanation: "Behaviour beats math when the plan you actually stick to is the one that works.",
      },
    ],
  },
  {
    slug: "l11",
    unitSlug: "u3",
    order: 2,
    title: "Your credit score",
    summary: "What moves it, and what doesn't.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "speedometer",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "The biggest factor in your credit score is…",
        options: ["Your age", "Payment history", "Your salary", "Number of cards you own"],
        answer: 1,
        explanation: "Paying on time, every time, matters more than anything else.",
      },
      {
        type: "true_false",
        prompt: "Checking your own credit score lowers it.",
        answer: false,
        explanation: "Self-checks (soft pulls) don't affect the score. Only lender-initiated hard pulls do.",
      },
      {
        type: "multiple_choice",
        prompt: "To improve your credit score, you should…",
        options: ["Max out every card", "Skip a payment now and then", "Pay on time and keep credit utilisation low", "Close all your oldest cards"],
        answer: 2,
        explanation: "On-time payments plus low utilisation (under 30%) are the two biggest levers.",
      },
      {
        type: "fill_number",
        prompt: "On a ₹1,00,000 credit limit, staying under 30% utilisation means using at most ₹___.",
        answer: 30000,
        explanation: "30% of 1,00,000 = 30,000.",
      },
    ],
  },

  // ---- Unit 4: Investing 101 --------------------------------------------------------
  {
    slug: "l12",
    unitSlug: "u4",
    order: 0,
    title: "Risk and return",
    summary: "The trade-off behind every investment.",
    xp: 20,
    estimatedMinutes: 4,
    icon: "pulse",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "In investing, higher potential returns almost always come with…",
        options: ["Lower risk", "Higher risk", "No risk at all", "Guaranteed losses"],
        answer: 1,
        explanation: "There is no free lunch — extra return is the reward for taking extra risk.",
      },
      {
        type: "true_false",
        prompt: "Fixed deposits are considered lower risk than stocks.",
        answer: true,
        explanation: "FDs have guaranteed returns; stock prices swing daily.",
      },
      {
        type: "multiple_choice",
        prompt: "'Diversification' means…",
        options: ["Buying one great stock", "Spreading money across different investments", "Timing the market perfectly", "Following hot tips"],
        answer: 1,
        explanation: "Don't put all your eggs in one basket. When one asset drops, another might hold.",
      },
    ],
  },
  {
    slug: "l13",
    unitSlug: "u4",
    order: 1,
    title: "What is a SIP?",
    summary: "Investing a little, every month.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "repeat",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "SIP stands for…",
        options: ["Special Investment Plan", "Systematic Investment Plan", "Small Income Product", "Standard Interest Payment"],
        answer: 1,
        explanation: "Systematic Investment Plan — a fixed amount invested at fixed intervals.",
      },
      {
        type: "true_false",
        prompt: "A SIP means investing a fixed amount at regular intervals, usually monthly.",
        answer: true,
        explanation: "You commit ₹X per month, and the platform buys units for you automatically.",
      },
      {
        type: "fill_number",
        prompt: "A ₹5,000/month SIP for 12 months invests ₹___ before any returns.",
        answer: 60000,
        explanation: "5,000 × 12 = 60,000. Actual value depends on market returns.",
      },
      {
        type: "multiple_choice",
        prompt: "The main benefit of SIPs is…",
        options: ["Guaranteed returns", "Rupee-cost averaging", "Zero fees", "Tax-free returns"],
        answer: 1,
        explanation: "You buy more units when prices are low and fewer when high — averaging out the cost.",
      },
    ],
  },
  {
    slug: "l14",
    unitSlug: "u4",
    order: 2,
    title: "Index funds",
    summary: "Own the whole market, cheaply.",
    xp: 30,
    estimatedMinutes: 5,
    icon: "grid",
    exercises: [
      {
        type: "multiple_choice",
        prompt: "An index fund is designed to…",
        options: ["Beat the market", "Match a market index", "Time the market", "Only hold 5 stocks"],
        answer: 1,
        explanation: "Index funds passively track an index (like the Nifty 50) — no stock picking.",
      },
      {
        type: "true_false",
        prompt: "Index funds usually have lower expense ratios than actively managed funds.",
        answer: true,
        explanation: "No fund manager picking stocks means lower costs, which compound in your favour.",
      },
      {
        type: "multiple_choice",
        prompt: "The Nifty 50 index tracks…",
        options: ["India's 50 largest listed companies", "The top 50 companies worldwide", "50 gold-mining companies", "50 Indian startups"],
        answer: 0,
        explanation: "Nifty 50 = the 50 largest companies on the NSE by market cap.",
      },
    ],
  },
];
